name: 'Thank You Action'
description: 'Sends thank you messages for opening/closing issues and issuing pull requests'
inputs:
  event-type:
    description: 'Type of event that triggered the action'
    required: true
runs:
  using: 'node'
  steps:
    - name: 'Set up Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
      
    - name: 'Send Thank You Message'
      run: |
        if [ "${{ github.event_name }}" == "issues" ]; then
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "Thanks for opening the issue, @${{ github.actor }}! We appreciate your contribution! 😊"
          elif [ "${{ github.event.action }}" == "closed" ]; then
            echo "Thanks for closing the issue, @${{ github.actor }}! Your contribution is valued! 👏"
          fi
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "Thanks for issuing the pull request, @${{ github.actor }}! We will review it soon. 🕵️‍♂️ If it's good, it will be merged; if not, we'll ask for some changes. 🛠️"
          fi
        fi
